# Example config to cross compile for the raspberry pi 4
# use like this: cargo build --config CrossCompileConfig.toml
# configure the paths to use your toolchain

[target.aarch64-unknown-linux-gnu]
linker = "/Users/ckl/development/aarch64-unknown-linux-gnu/bin/aarch64-unknown-linux-gnu-g++"

[env]
CXX = { value = "/Users/ckl/development/aarch64-unknown-linux-gnu/bin/aarch64-unknown-linux-gnu-g++", forced = true }
AR = { value = "/Users/ckl/development/aarch64-unknown-linux-gnu/bin/aarch64-unknown-linux-gnu-ar", forced = true }
CC = { value = "/Users/ckl/development/aarch64-unknown-linux-gnu/bin/aarch64-unknown-linux-gnu-cc", forced = true }

[build]
target = "aarch64-unknown-linux-gnu"
